// <auto-generated />
using System;
using GoodHamburger.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260424155707_primeriaMigration")]
    partial class primeriaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburger.Infra.Entities.Acompanhamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Acompanhamentos");
                });

            modelBuilder.Entity("GoodHamburger.Infra.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<int?>("SanduicheId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanduicheId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GoodHamburger.Infra.Entities.Sanduiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sanduiches");
                });

            modelBuilder.Entity("GoodHamburger.Infra.Entities.Acompanhamento", b =>
                {
                    b.HasOne("GoodHamburger.Infra.Entities.Pedido", null)
                        .WithMany("Acompanhamentos")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("GoodHamburger.Infra.Entities.Pedido", b =>
                {
                    b.HasOne("GoodHamburger.Infra.Entities.Sanduiche", "Sanduiche")
                        .WithMany()
                        .HasForeignKey("SanduicheId");

                    b.Navigation("Sanduiche");
                });

            modelBuilder.Entity("GoodHamburger.Infra.Entities.Pedido", b =>
                {
                    b.Navigation("Acompanhamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
